version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: finance
    ports:
      - 5432:5432
  app: 
    image: financeproj
    ports: 
      - 3000:3000
    depends_on:
      - db
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: finance
    