name: TESTnLINT

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@latest
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}

  docker-compose-test:
    name: Build and Run Test in Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Run Tests
        run: docker-compose up --build test


      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
